// Pure, testable core of the Genesis local-bot installer (BRO-1534).
//
// Everything here is side-effect-free: OS detection, config derivation, and the
// rendering of env.sh / secrets.env / start scripts / launchd plists / systemd
// units. The CLI (cli.ts) does the I/O (prompts, fs writes, launchctl/systemctl)
// and calls these to produce the file bodies.

export type OS = "macos" | "linux";

export function detectOS(platform: string = process.platform): OS {
  if (platform === "darwin") return "macos";
  if (platform === "linux") return "linux";
  throw new Error(
    `unsupported platform "${platform}" — Genesis local-bot installs on macOS or Linux`,
  );
}

export interface InstallInputs {
  os: OS;
  home: string;
  /** Absolute path to the genesis repo checkout (where `apps/api` lives). */
  repoDir: string;
  /** Telegram bot token (→ secrets.env, 0600). */
  botToken: string;
  /** Resolved @username from getMe (display only). */
  botUsername: string;
  /** Owner Telegram chat id(s), comma-separated — the allowlist. REQUIRED. */
  allowedUsers: string;
  /** The real workspace the agent operates on. */
  workspace: string;
  /** API port. */
  port: number;
  /** Absolute dirs to prepend to PATH so the service finds bun/claude/tmux/git
   *  under the minimal PATH launchd/systemd give. */
  pathDirs: string[];
}

export interface Paths {
  configDir: string;
  dataDir: string;
  stateDir: string;
  logDir: string;
  secretsFile: string;
  envFile: string;
  apiStart: string;
  botStart: string;
}

/** Canonical install paths (XDG-ish; identical layout on macOS + Linux except logs). */
export function paths(os: OS, home: string): Paths {
  const configDir = `${home}/.config/genesis-bot`;
  const logDir = os === "macos" ? `${home}/Library/Logs` : `${configDir}/logs`;
  return {
    configDir,
    dataDir: `${configDir}/data`,
    stateDir: `${configDir}/state`,
    logDir,
    secretsFile: `${configDir}/secrets.env`,
    envFile: `${configDir}/env.sh`,
    apiStart: `${configDir}/start-api.sh`,
    botStart: `${configDir}/start-bot.sh`,
  };
}

/** secrets.env — bare VAR=value, sourced under `set -a`. 0600 on disk. */
export function renderSecretsEnv(botToken: string): string {
  return [
    "# Genesis bot secret — sourced by env.sh via `set -a` (bare VAR=value).",
    "# Owner-specific, 0600, NEVER in git or the service unit. (BRO-1527/1534)",
    `TELEGRAM_BOT_TOKEN=${botToken}`,
    "",
  ].join("\n");
}

/** env.sh — the environment both start scripts source. Cross-platform. */
export function renderEnvSh(i: InstallInputs, p: Paths): string {
  const pathLine = [...i.pathDirs, "$PATH"].join(":");
  return `# Genesis local bot — service environment. Generated by \`genesis install\` (BRO-1534).
# Owner-specific; keep OUT of git. Re-run \`genesis install\` to regenerate.

# launchd/systemd give a minimal PATH — prepend the real tool dirs so the agent
# can find bun, claude (and tmux for the interactive engine).
export PATH="${pathLine}"

# Engine: PRINT (\`claude -p\`) — simple, reliable, draws the subscription at no
# penalty while Anthropic's Agent-SDK metering stays paused. To use the exempt
# interactive engine instead, set GENESIS_ENGINE=interactive and drop
# GENESIS_AGENT_ARGS (requires tmux).
# export GENESIS_ENGINE=interactive
export GENESIS_AGENT_ARGS="--dangerously-skip-permissions"

export GENESIS_WORKSPACE="${i.workspace}"
export GENESIS_NO_WORKTREE=1
export GENESIS_DATA_DIR="${p.dataDir}"
export GENESIS_BOT_STATE_DIR="${p.stateDir}"

export PORT=${i.port}
export GENESIS_URL=http://localhost:${i.port}
export TELEGRAM_BOT_USERNAME="${i.botUsername}"
# REQUIRED: only these Telegram chat ids may drive the bot. Without it, anyone
# who DMs the bot gets code execution on this machine.
export GENESIS_TELEGRAM_ALLOWED_USERS=${i.allowedUsers}

# Token from the 0600 secret file (never in the service unit).
set -a
source "${p.secretsFile}"
set +a
`;
}

/** A start wrapper (api|bot) run by the service. cd to the repo so cwd is stable. */
export function renderStartScript(i: InstallInputs, p: Paths, which: "api" | "bot"): string {
  const entry = which === "api" ? "apps/api/src/index.ts" : "apps/chat-bot/src/index.ts";
  return `#!/bin/bash
# Genesis ${which} — started by the service manager. Generated by \`genesis install\`.
set -euo pipefail
source "${p.envFile}"
cd "${i.repoDir}"
exec bun ${entry}
`;
}

const LABEL = { api: "tech.broomva.genesis.api", bot: "tech.broomva.genesis.bot" } as const;
const UNIT = { api: "genesis-api", bot: "genesis-bot" } as const;

/** Stable service identifier per OS (launchd label / systemd unit name). */
export function serviceId(os: OS, which: "api" | "bot"): string {
  return os === "macos" ? LABEL[which] : `${UNIT[which]}.service`;
}

/** macOS launchd LaunchAgent plist. */
export function renderLaunchdPlist(i: InstallInputs, p: Paths, which: "api" | "bot"): string {
  const start = which === "api" ? p.apiStart : p.botStart;
  const log = `${p.logDir}/genesis-${which}.log`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL[which]}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${start}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${i.repoDir}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${log}</string>
  <key>StandardErrorPath</key>
  <string>${log}</string>
</dict>
</plist>
`;
}

/** Linux systemd --user service unit. */
export function renderSystemdUnit(i: InstallInputs, p: Paths, which: "api" | "bot"): string {
  const start = which === "api" ? p.apiStart : p.botStart;
  const desc = which === "api" ? "Genesis api (Hono/Bun)" : "Genesis Telegram bot";
  const after = which === "bot" ? "\nAfter=genesis-api.service\nWants=genesis-api.service" : "";
  return `[Unit]
Description=${desc}
After=network-online.target${after}
Wants=network-online.target

[Service]
Type=simple
ExecStart=/bin/bash ${start}
WorkingDirectory=${i.repoDir}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
`;
}

/** Parse a Telegram getMe response body. Returns the bot username when ok. */
export function parseGetMe(body: unknown): { ok: boolean; username?: string; reason?: string } {
  if (typeof body !== "object" || body === null)
    return { ok: false, reason: "non-object response" };
  const b = body as { ok?: unknown; result?: { username?: unknown }; description?: unknown };
  if (b.ok !== true) {
    return {
      ok: false,
      reason: typeof b.description === "string" ? b.description : "token rejected",
    };
  }
  const username = b.result?.username;
  return { ok: true, username: typeof username === "string" ? username : undefined };
}

/** A Telegram bot token looks like `<digits>:<35+ url-safe chars>`. Shape-only. */
export function looksLikeToken(s: string): boolean {
  return /^\d{6,}:[A-Za-z0-9_-]{30,}$/.test(s.trim());
}

export interface ParsedArgs {
  command: string;
  flags: Record<string, string>;
  bools: Set<string>;
}

/** Minimal arg parser: `cmd --key=val --key val --flag`. */
export function parseArgs(argv: readonly string[]): ParsedArgs {
  const [command = "help", ...rest] = argv;
  const flags: Record<string, string> = {};
  const bools = new Set<string>();
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (!a || !a.startsWith("--")) continue;
    const body = a.slice(2);
    const eq = body.indexOf("=");
    if (eq >= 0) {
      flags[body.slice(0, eq)] = body.slice(eq + 1);
    } else {
      const next = rest[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        flags[body] = next;
        i++;
      } else {
        bools.add(body);
      }
    }
  }
  return { command, flags, bools };
}
